site_name: arxiv2024_obscuracoder
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: arxiv2024_obscuracoder
      handlers:
        python:
          options:
            docstring_style: numpy